import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class LogoutWindow extends javax.swing.JFrame {

	public static LoginGUI LG;
	public static LogoutWindow logout;
	public static NetBeansCatCafeMenu menu;
	
    /**
     * Creates new form Logout
     */
    public LogoutWindow(LoginGUI p1) {
    	LG = p1;
    	logout = this; //can use the word this instead of logout in code
    
        initComponents();
        this.setResizable(false);
        this.setSize(550, 330);
    }
    
    public void setMenu(NetBeansCatCafeMenu p3) {
    	menu = p3;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setText("Thank you for dining at Cat Cafe.");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jLabel2.setText("Please come again!");

        jButton1.setText("NEW ORDER");
        jButton1.addActionListener(new ActionListener() { 
    		public void actionPerformed(ActionEvent f) {
    
    			menu.jTextArea1.setText(" ");
    			
               for(int i = 0; i < menu.js.size(); i++) {
            	   menu.js.get(i).setValue(0);
            	   menu.getjTextField50().setText("             ");
               }
    			 
                
                
                //new order method
    			
    			logout.setVisible(false);
           		menu.setVisible(true);
            }
        });

        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new ActionListener() { 
    		public void actionPerformed(ActionEvent e) {
    			logout.setVisible(false);
          		 LG.setVisible(true);
    		}
    });

        
        jButton3.setText("RETURN TO ORDER");
        jButton3.addActionListener(new ActionListener() {
       	public void actionPerformed(ActionEvent e)
       	{
       		logout.setVisible(false);
       		menu.setVisible(true);
       	}
       });
        
        jLabel5.setIcon(new javax.swing.ImageIcon("CatPawLick.png")); 

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); 
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
               //  .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addComponent(jButton3)
                        .addGap(78, 78, 78)
                        .addComponent(jButton2)
                      //  .addGap(93, 93, 93)
                        )))
            
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
